import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "another meta data to help us in search engine optimization but custom inside specific page ",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div>Sub Root Layout
         {children}
      </div>
       

  );
}
